export const languages = [
  ['en', 'English'], ['de', 'Deutsch'], ['fr', 'Français'], ['ru', 'Русский'],
  ['es', 'Español'], ['pt', 'Português'], ['zh', '中文'], ['tr', 'Türkçe'],
];

const en = {
  subtitle: 'ETS2 / ATS webcam tracker', ready: 'Ready', language: 'Language', camera: 'Camera',
  privacy: 'Video is processed only on this computer.', fps: '{value} FPS', stoppedTitle: 'Tracking has not started',
  stoppedBody: 'Select your camera and press Start.', yaw: 'LEFT / RIGHT', pitch: 'UP / DOWN', roll: 'ROLL',
  controls: 'Controls', cameraLabel: 'Camera', defaultCamera: 'Default camera', cameraNumber: 'Camera {value}',
  headGain: 'Head sensitivity', eyeGain: 'Eye contribution', smoothing: 'Smoothing', deadzone: 'Dead zone',
  invertYaw: 'Reverse left/right', invertPitch: 'Reverse up/down', invertRoll: 'Reverse roll',
  start: 'Start tracking', stop: 'Stop tracking', center: 'Recenter', appReady: 'Ready', running: 'Running',
  notRunning: 'Not running', closed: 'Closed', openTrackSettings: 'OpenTrack setup',
  openTrackHint: 'Input: UDP over network · Filter: None|Output: freetrack 2.0 Enhanced → TrackIR',
  localProcessing: 'Local processing · No recording', modelLoading: 'Loading tracking model…',
  calibrating: 'Look at the center… {value}s', sending: 'Sending to OpenTrack', openTrackMissing: 'OpenTrack is not running',
  faceMissing: 'Face not found', trackingError: 'Tracking error', permissionDenied: 'Camera permission denied',
  startFailed: 'Could not start', hiddenTitle: 'Tracking is active',
  hiddenBody: 'Camera preview is hidden to reduce rendering load. Recenter to show it for 5 seconds.',
};

export const translations = {
  en,
  de: { ...en, subtitle:'ETS2 / ATS Webcam-Tracker', ready:'Bereit', language:'Sprache', camera:'Kamera', privacy:'Das Video wird nur auf diesem Computer verarbeitet.', stoppedTitle:'Tracking wurde noch nicht gestartet', stoppedBody:'Kamera auswählen und auf Start klicken.', yaw:'LINKS / RECHTS', pitch:'OBEN / UNTEN', roll:'NEIGUNG', controls:'Steuerung', cameraLabel:'Kamera', defaultCamera:'Standardkamera', cameraNumber:'Kamera {value}', headGain:'Kopf-Empfindlichkeit', eyeGain:'Augenanteil', smoothing:'Glättung', deadzone:'Totzone', invertYaw:'Links/Rechts umkehren', invertPitch:'Oben/Unten umkehren', invertRoll:'Neigung umkehren', start:'Tracking starten', stop:'Tracking stoppen', center:'Zentrieren', appReady:'Bereit', running:'Läuft', notRunning:'Läuft nicht', closed:'Geschlossen', openTrackSettings:'OpenTrack-Einstellung', openTrackHint:'Eingang: UDP over network · Filter: None|Ausgang: freetrack 2.0 Enhanced → TrackIR', localProcessing:'Lokale Verarbeitung · Keine Aufnahme', modelLoading:'Tracking-Modell wird geladen…', calibrating:'In die Mitte schauen… {value}s', sending:'Wird an OpenTrack gesendet', openTrackMissing:'OpenTrack läuft nicht', faceMissing:'Gesicht nicht gefunden', trackingError:'Tracking-Fehler', permissionDenied:'Kamerazugriff verweigert', startFailed:'Start nicht möglich', hiddenTitle:'Tracking ist aktiv', hiddenBody:'Die Kameravorschau ist ausgeblendet, um die Renderlast zu senken. Zentrieren zeigt sie 5 Sekunden lang.' },
  fr: { ...en, subtitle:'Suivi webcam pour ETS2 / ATS', ready:'Prêt', language:'Langue', camera:'Caméra', privacy:'La vidéo est traitée uniquement sur cet ordinateur.', stoppedTitle:"Le suivi n'est pas démarré", stoppedBody:'Sélectionnez la caméra puis appuyez sur Démarrer.', yaw:'GAUCHE / DROITE', pitch:'HAUT / BAS', roll:'INCLINAISON', controls:'Commandes', cameraLabel:'Caméra', defaultCamera:'Caméra par défaut', cameraNumber:'Caméra {value}', headGain:'Sensibilité de la tête', eyeGain:'Contribution des yeux', smoothing:'Lissage', deadzone:'Zone morte', invertYaw:'Inverser gauche/droite', invertPitch:'Inverser haut/bas', invertRoll:"Inverser l'inclinaison", start:'Démarrer le suivi', stop:'Arrêter le suivi', center:'Recentrer', appReady:'Prêt', running:'Actif', notRunning:'Inactif', closed:'Fermé', openTrackSettings:'Réglage OpenTrack', openTrackHint:'Entrée : UDP over network · Filtre : None|Sortie : freetrack 2.0 Enhanced → TrackIR', localProcessing:'Traitement local · Aucun enregistrement', modelLoading:'Chargement du modèle…', calibrating:'Regardez au centre… {value}s', sending:'Envoi vers OpenTrack', openTrackMissing:"OpenTrack n'est pas actif", faceMissing:'Visage introuvable', trackingError:'Erreur de suivi', permissionDenied:'Accès caméra refusé', startFailed:'Démarrage impossible', hiddenTitle:'Le suivi est actif', hiddenBody:"L’aperçu caméra est masqué pour réduire la charge graphique. Recentrez pour l’afficher pendant 5 secondes." },
  ru: { ...en, subtitle:'Веб-камера трекер для ETS2 / ATS', ready:'Готово', language:'Язык', camera:'Камера', privacy:'Видео обрабатывается только на этом компьютере.', stoppedTitle:'Отслеживание не запущено', stoppedBody:'Выберите камеру и нажмите «Запустить».', yaw:'ВЛЕВО / ВПРАВО', pitch:'ВВЕРХ / ВНИЗ', roll:'НАКЛОН', controls:'Управление', cameraLabel:'Камера', defaultCamera:'Камера по умолчанию', cameraNumber:'Камера {value}', headGain:'Чувствительность головы', eyeGain:'Вклад взгляда', smoothing:'Сглаживание', deadzone:'Мёртвая зона', invertYaw:'Инверсия влево/вправо', invertPitch:'Инверсия вверх/вниз', invertRoll:'Инверсия наклона', start:'Запустить отслеживание', stop:'Остановить отслеживание', center:'Центрировать', appReady:'Готово', running:'Работает', notRunning:'Не работает', closed:'Закрыто', openTrackSettings:'Настройка OpenTrack', openTrackHint:'Вход: UDP over network · Фильтр: None|Выход: freetrack 2.0 Enhanced → TrackIR', localProcessing:'Локальная обработка · Без записи', modelLoading:'Загрузка модели…', calibrating:'Смотрите в центр… {value}с', sending:'Отправка в OpenTrack', openTrackMissing:'OpenTrack не запущен', faceMissing:'Лицо не найдено', trackingError:'Ошибка отслеживания', permissionDenied:'Нет доступа к камере', startFailed:'Не удалось запустить', hiddenTitle:'Отслеживание активно', hiddenBody:'Предпросмотр камеры скрыт для снижения нагрузки. Центрирование покажет его на 5 секунд.' },
  es: { ...en, subtitle:'Seguimiento por webcam para ETS2 / ATS', ready:'Listo', language:'Idioma', camera:'Cámara', privacy:'El vídeo se procesa únicamente en este equipo.', stoppedTitle:'El seguimiento no ha comenzado', stoppedBody:'Selecciona la cámara y pulsa Iniciar.', yaw:'IZQUIERDA / DERECHA', pitch:'ARRIBA / ABAJO', roll:'INCLINACIÓN', controls:'Controles', cameraLabel:'Cámara', defaultCamera:'Cámara predeterminada', cameraNumber:'Cámara {value}', headGain:'Sensibilidad de cabeza', eyeGain:'Contribución ocular', smoothing:'Suavizado', deadzone:'Zona muerta', invertYaw:'Invertir izquierda/derecha', invertPitch:'Invertir arriba/abajo', invertRoll:'Invertir inclinación', start:'Iniciar seguimiento', stop:'Detener seguimiento', center:'Centrar', appReady:'Listo', running:'Activo', notRunning:'Inactivo', closed:'Cerrado', openTrackSettings:'Configuración de OpenTrack', openTrackHint:'Entrada: UDP over network · Filtro: None|Salida: freetrack 2.0 Enhanced → TrackIR', localProcessing:'Procesamiento local · Sin grabación', modelLoading:'Cargando modelo…', calibrating:'Mira al centro… {value}s', sending:'Enviando a OpenTrack', openTrackMissing:'OpenTrack no está activo', faceMissing:'No se encontró el rostro', trackingError:'Error de seguimiento', permissionDenied:'Permiso de cámara denegado', startFailed:'No se pudo iniciar', hiddenTitle:'Seguimiento activo', hiddenBody:'La vista de la cámara está oculta para reducir la carga gráfica. Centrar la mostrará durante 5 segundos.' },
  pt: { ...en, subtitle:'Rastreador por webcam para ETS2 / ATS', ready:'Pronto', language:'Idioma', camera:'Câmara', privacy:'O vídeo é processado apenas neste computador.', stoppedTitle:'O rastreamento não foi iniciado', stoppedBody:'Selecione a câmara e pressione Iniciar.', yaw:'ESQUERDA / DIREITA', pitch:'CIMA / BAIXO', roll:'INCLINAÇÃO', controls:'Controlos', cameraLabel:'Câmara', defaultCamera:'Câmara predefinida', cameraNumber:'Câmara {value}', headGain:'Sensibilidade da cabeça', eyeGain:'Contribuição dos olhos', smoothing:'Suavização', deadzone:'Zona morta', invertYaw:'Inverter esquerda/direita', invertPitch:'Inverter cima/baixo', invertRoll:'Inverter inclinação', start:'Iniciar rastreamento', stop:'Parar rastreamento', center:'Recentralizar', appReady:'Pronto', running:'Em execução', notRunning:'Parado', closed:'Fechado', openTrackSettings:'Configuração do OpenTrack', openTrackHint:'Entrada: UDP over network · Filtro: None|Saída: freetrack 2.0 Enhanced → TrackIR', localProcessing:'Processamento local · Sem gravação', modelLoading:'A carregar o modelo…', calibrating:'Olhe para o centro… {value}s', sending:'A enviar para OpenTrack', openTrackMissing:'O OpenTrack não está em execução', faceMissing:'Rosto não encontrado', trackingError:'Erro de rastreamento', permissionDenied:'Permissão da câmara recusada', startFailed:'Não foi possível iniciar', hiddenTitle:'Rastreamento ativo', hiddenBody:'A pré-visualização está oculta para reduzir a carga gráfica. Recentralize para a mostrar durante 5 segundos.' },
  zh: { ...en, subtitle:'ETS2 / ATS 摄像头头部追踪器', ready:'就绪', language:'语言', camera:'摄像头', privacy:'视频仅在本机处理。', stoppedTitle:'尚未开始追踪', stoppedBody:'选择摄像头并点击开始。', yaw:'左 / 右', pitch:'上 / 下', roll:'倾斜', controls:'控制', cameraLabel:'摄像头', defaultCamera:'默认摄像头', cameraNumber:'摄像头 {value}', headGain:'头部灵敏度', eyeGain:'眼动权重', smoothing:'平滑度', deadzone:'死区', invertYaw:'反转左右', invertPitch:'反转上下', invertRoll:'反转倾斜', start:'开始追踪', stop:'停止追踪', center:'重新居中', appReady:'就绪', running:'运行中', notRunning:'未运行', closed:'已关闭', openTrackSettings:'OpenTrack 设置', openTrackHint:'输入：UDP over network · 滤镜：None|输出：freetrack 2.0 Enhanced → TrackIR', localProcessing:'本地处理 · 不录像', modelLoading:'正在加载追踪模型…', calibrating:'请看向屏幕中央… {value}秒', sending:'正在发送到 OpenTrack', openTrackMissing:'OpenTrack 未运行', faceMissing:'未检测到人脸', trackingError:'追踪错误', permissionDenied:'摄像头权限被拒绝', startFailed:'无法启动', hiddenTitle:'追踪已启用', hiddenBody:'为降低渲染负载，摄像头预览已隐藏。重新居中时将显示 5 秒。' },
  tr: { ...en, subtitle:'ETS2 / ATS webcam takipçisi', ready:'Hazır', language:'Dil', camera:'Kamera', privacy:'Görüntü yalnızca bu bilgisayarda işlenir.', stoppedTitle:'Takip henüz başlamadı', stoppedBody:"Kameranı seçip Başlat'a bas.", yaw:'SAĞ / SOL', pitch:'YUKARI / AŞAĞI', roll:'YATIRMA', controls:'Kontroller', cameraLabel:'Kamera', defaultCamera:'Varsayılan kamera', cameraNumber:'Kamera {value}', headGain:'Kafa hassasiyeti', eyeGain:'Göz katkısı', smoothing:'Yumuşatma', deadzone:'Ölü bölge', invertYaw:'Sağ/sol yönünü ters çevir', invertPitch:'Yukarı/aşağı yönünü ters çevir', invertRoll:'Yatırma yönünü ters çevir', start:'Takibi başlat', stop:'Takibi durdur', center:'Merkezle', appReady:'Hazır', running:'Çalışıyor', notRunning:'Çalışmıyor', closed:'Kapalı', openTrackSettings:'OpenTrack ayarı', openTrackHint:'Giriş: UDP over network · Filtre: None|Çıkış: freetrack 2.0 Enhanced → TrackIR', localProcessing:'Yerel görüntü işleme · Kayıt yapılmaz', modelLoading:'Takip modeli yükleniyor…', calibrating:'Ekranın ortasına bakın… {value} sn', sending:'OpenTrack’e gönderiliyor', openTrackMissing:'OpenTrack çalışmıyor', faceMissing:'Yüz bulunamadı', trackingError:'Takip hatası', permissionDenied:'Kamera izni reddedildi', startFailed:'Başlatılamadı', hiddenTitle:'Takip aktif', hiddenBody:'Kaynak kullanımını azaltmak için kamera önizlemesi gizlendi. Merkezle düğmesi görüntüyü 5 saniye açar.' },
};

export function resolveLanguage(value = navigator.language) {
  const code = String(value).toLowerCase().split('-')[0];
  return translations[code] ? code : 'en';
}

export function translate(language, key, values = {}) {
  let text = translations[language]?.[key] ?? en[key] ?? key;
  for (const [name, value] of Object.entries(values)) text = text.replaceAll(`{${name}}`, value);
  return text;
}
